### ISSUE TITLE
An issue with 6.2 of Levelhead...

### ISSUE THREAD

**Issue by OPAmqericaHPE** [Sk1erLLC/Levelhead#15]
Alright, so I tried out Levelhead 6.2 and I'm still crashing, but with a different error while the mod is in my mods folder. Here's my issue with the mod:

So I launch Minecraft. Completely normal.
I click on 'Multiplayer' and go to Hypixel.
Then when I join the server, it crashes after a split second saying "Error whilst rendering entity."

This might be my end, but I'm not sure. I have multiple crash reports from a few days ago with this crash.
I put them all in a gist:

https://gist.github.com/OPAmqericaHPE/b6d523ca89d7bc8faf11f9c15c5bdc72

**Comment by SlenderMcEnder** [comment]
I'm having the same problem

**Comment by FalseHonesty** [comment]
I've fixed a possible source of this in commit 840f941e5c420b50275889dc84b80d85be4c919f. I'll update you when the new jar has been published to the website. Thank you for your help!

**Comment by OPAmqericaHPE** [comment]
Still having issues. I'm not sure if it's my computer being stupid with Minecraft, but yet again, crashing. here's a crash report because of it: https://gist.github.com/OPAmqericaHPE/ef976beabb9053023ad3342f31e4ca94

**Comment by OPAmqericaHPE** [comment]
This hasn't been replied to in 10 days. Do I have to close this request or just wait?

**Comment by FalseHonesty** [comment]
We'll look into this ASAP, thanks for the reminder.

**Comment by FalseHonesty** [comment]
Should hopefully be mitigated in 585b7f175dcafc6ed3964302cc546edf3d9a3da1.

**Comment by OPAmqericaHPE** [comment]
Ok. Should I try Levelhead 6.3?

**Comment by OPAmqericaHPE** [comment]
Hello! This hasn't been replied to in 18 days. Is there anything going on?

**Comment by OPAmqericaHPE** [comment]
Hi! I forgot to ask. Is there a new Levelhead being worked on? 6.3 still crashes.

https://gist.github.com/OPAmqericaHPE/9ddb4eb5f8074a0413f4333bb5c47efd

This is the crash report just incase.

**Comment by Sk1er** [comment]
Hi, 
We do plan on updating Levelhead in the future. However, all of our development resources are focused on Frames+ currently. Once that project has launched, we will return to our other project.s

**Comment by OPAmqericaHPE** [comment]
Oh, alright! That answers my question! Can't wait!
